var questions = [{
    q1: "In which country is the Taj Mahal?",
    o1: "America",
    o2: "India",
    o3: "Pakistan",
    o4: "Australia",
    a: 2,
},
{
    q2:"Who was the first man to walk on the moon?",
    o1: "Kalpana Chawla",
    o2: "Edwin Aldrin",
    o3: "Neil Armstrong",
    o4: "Pete Conrad",
    a: 3,
},
{
    q3: "whch one is the Southern Ocean called?",
    o1: "PACIFIC OCEAN",
    o2: "ARCTIC OCEAN",
    o3: "INDIAN OCEAN",
    o4: "ANTARCTIC OCEAN",
    a: 4,
},
{
    q4: "Which language is spoken in Australia?",
    o1: "English",
    o2: "Hindi",
    o3: "Spanish",
    o4: "french",
    a: 1,
},
{
    q5: "What is the name of the tree that produces acorns?",
    o1: "Fir",
    o2: "Oak",
    o3: "Mango",
    o4: "Apple",
    a: 2,
},
{
    q6: "What is a baby kangaroo called?",
    o1: "Pup",
    o2: "joey",
    o3: "Cub",
    o4: "Calf",
    a: 2,
},
{
    q7: "How many sides does a hexagon have?",
    o1: "Four",
    o2: "Seven",
    o3: "Six",
    o4: "Eight",
    a: 3,
},
{
    q8: "How many strings does a violin have?",
    o1: "Five",
    o2: "Four",
    o3: "Six",
    o4: "three",
    a: 2,
},
{
    q9: "What is the highest mountain in Great Britain?",
    o1: "Ben Nevis",
    o2: "Carn Eige",
    o3: "Snowdon - Yr Wyddfa",
    o4: "Carrauntoohil",
    a: 1,
},
{
    q10: "What is the capital of New Zealand?",
    o1: "Canberra",
    o2: "Wellington",
    o3: "Havana",
    o4: "Jakarta",
    a: 2,
},
{
    q11:"The Great Barrier Reef is located in which country?",
    o1: "Australia",
    o2: "America",
    o3: "Britain",
    o4: "Finland",
    a: 1,
},
{
    q12: "What sort of animal is the video game character Sonic?",
    o1: "Hedgehog",
    o2: "Rabbit",
    o3: "Hamster",
    o4: "Mouse",
    a: 1,
},
{
    q13: "Helsinki is the capital city of which country?",
    o1: "Island",
    o2: "Finland",
    o3: "Iran",
    o4: "Japan",
    a: 2,
},
{
    q14: "On which continent is India located?",
    o1: "Europe",
    o2: "Asia",
    o3: "North America",
    o4: "South America",
    a: 2,
},
{
    q15: "What is the name given to an animal that only eats plants?",
    o1: "Carnivorous",
    o2: "Omnivore",
    o3: "Herbivore",
    o4: "None",
    a: 3,
},{
    q16: "In which year did the Second World War end?",
    o1: "1914",
    o2: "1945",
    o3: "1939",
    o4: "1918",
    a: 2,
},{
    q17: "What is the name of the organ that pumps blood around the body?",
    o1: "Heart",
    o2: "Lungs",
    o3: "Kidney",
    o4: "Lever",
    a: 1,
},{
    q18: "What two colours make up the flag of Spain?",
    o1: "Red and blue",
    o2: "Blue and yellow",
    o3: "Red and yellow",
    o4: "Green and blue",
    a: 3,
},{
    q19: "How many hours are there in two days?",
    o1: "24",
    o2: "48",
    o3: "72",
    o4: "12",
    a: 2,
},{
    q20: "What is a baby goat called?",
    o1: "Pup",
    o2: "Cub",
    o3: "Goat",
    o4: "Kid",
    a: 4,
},
]






